export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'

export const GET_PATIENTS = 'GET_PATIENTS'
export const GET_TODAYS_PATIENTS = 'GET_TODAYS_PATIENTS'

export const SELECTED_PATIENT = 'SELECTED_PATIENT'
export const DESELECT_PATIENT = 'DESELECT_PATIENT'
export const UPDATE_HEALTH_DATA = 'UPDATE_HEALTH_DATA'

export const CLICK_WIDGET = 'CLICK_WIDGET'

export const DISPLAY_WIDGET = 'DISPLAY_WIDGET'

export const SELECT_CURRENT_CONTACT = 'SELECT_CURRENT_CONTACT'
export const DESELECT_CURRENT_CONTACT = 'DESELECT_CURRENT_CONTACT'

export const SET_HISTORY = 'SET_HISTORY'

export const LOADING = 'LOADING'

export const CLOSE_WIDGETS = 'CLOSE_WIDGETS'