export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'

export const GET_PATIENTS = 'GET_PATIENTS'

export const SELECTED_PATIENT = 'SELECTED_PATIENT'
export const DESELECT_PATIENT = 'DESELECT_PATIENT'
export const UPDATE_HEALTH_DATA = 'UPDATE_HEALTH_DATA'

export const CLICK_WIDGET = 'CLICK_WIDGET'

export const DISPLAY_WIDGET = 'DISPLAY_WIDGET'